### ISSUE TITLE
Code is not uploaded

### ISSUE THREAD

**Issue by winfried-ripken** [rish-16/grafog#1]
Thanks for the contribution, I am missing the py files in grafog. Also pip install seems to be not working.
Are you planning on adding more content?

**Comment by rish-16** [comment]
Hello, it's still a WIP! Will have it out in the next two weeks

Appreciate your patience and enthusiasm to try it out 🙌🏻

**Comment by winfried-ripken** [comment]
Very cool, looking forward!

**Comment by chasingtim** [comment]
Thanks for the contribution, may i ask will it be uploaded in the next few days?

**Comment by rish-16** [comment]
Yup! Will be released this coming week 😃 

@chasingtim
